---
- name: stop contrail config service
  community.docker.docker_compose_v2:
    project_src: /etc/contrail/config
    state: absent
  environment:
    DOCKER_CLIENT_TIMEOUT: '120'
    COMPOSE_HTTP_TIMEOUT: '120'
