---
- name: stop contrail analytics_snmp
  community.docker.docker_compose_v2:
    project_src: /etc/contrail/analytics_snmp
    state: absent
  environment:
    DOCKER_CLIENT_TIMEOUT: '120'
    COMPOSE_HTTP_TIMEOUT: '120'
