- name: update opensdn-snmp-collector and opensdn-analytics-snmp-topology image
  shell: "docker pull {{ container_registry }}/{{ item }}:{{ contrail_version_tag }}"
  register: res
  retries: 5
  until: res.rc == 0
  with_items:
    - opensdn-node-init
    - opensdn-nodemgr
    - opensdn-analytics-snmp-topology
    - opensdn-analytics-snmp-collector
    - opensdn-provisioner
  when:
   - contrail_configuration.UPDATE_IMAGES is undefined or contrail_configuration.UPDATE_IMAGES != false
   - roles[instance_name].analytics_snmp is defined
