- name: setup debug
  setup:
  register: stat
- name: update contrail rsyslogd image
  shell: "docker pull {{ container_registry }}/{{ item }}:{{ contrail_version_tag }}"
  register: res
  retries: 5
  until: res.rc == 0
  with_items:
    - opensdn-external-rsyslogd
  when:
    - contrail_configuration.UPDATE_IMAGES is undefined or contrail_configuration.UPDATE_IMAGES != false
    - roles[instance_name].vrouter is defined and stat.ansible_facts.ansible_system == 'Linux'
