---
- name: "Stop contrail control"
  community.docker.docker_compose_v2:
    project_src: /etc/contrail/control
    state: absent
  environment:
    DOCKER_CLIENT_TIMEOUT: '120'
    COMPOSE_HTTP_TIMEOUT: '120'
